import { Footer } from "@/components/footer"
import { MainNav } from "@/components/main-nav"
import type { Metadata } from "next"
import { Playfair_Display, Work_Sans } from "next/font/google"
import "./globals.css"

const playfair = Playfair_Display({
    variable: "--font-playfair-display",
    subsets: ["latin"],
})

const workSans = Work_Sans({
    variable: "--font-work-sans",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${playfair.variable} ${workSans.variable} antialiased`}
            >
                <MainNav />
                {children}
                <Footer />
            </body>
        </html>
    )
}
